# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: mixed-line-ending
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        args:
            - --line-length=99
            - --target-version=py38
-   repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
            - --in-place
            - --recursive
            - --remove-all-unused-imports
            - --remove-duplicate-keys
            - --remove-unused-variables
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: [--max-line-length=99]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.0.8
    hooks:
    -   id: isort
        args: [--profile=black]
# https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/
-   repo: local
    hooks:
    -   id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
- repo: local
  hooks:
    - id: dvc-push-to-remote
      name: dvc-push-to-remote
      stages: [push]
      entry: scripts/utils/push-hook.sh
      language: system
